package com.simats.farmmillet

object AppRoutes {
    const val WELCOME = "welcome"
    const val ROLE_SELECTION = "role_selection"

    const val FARMER_LOGIN = "farmer_login"
    const val FARMER_RESET_PASSWORD = "farmer_reset_password"
    const val FARMER_VERIFICATION_CODE = "farmer_verification_code/{email}"
    const val FARMER_SET_NEW_PASSWORD = "farmer_set_new_password"
    const val FARMER_DASHBOARD = "farmer_dashboard"
    const val FARMER_PROFILE = "farmer_profile"
    const val FARMER_PASSWORD = "farmer_password"

    const val SHG_FPO_LOGIN = "shg_fpo_login"
    const val SHG_FPO_RESET_PASSWORD = "shg_fpo_reset_password"
    const val SHG_FPO_VERIFICATION_CODE = "shg_fpo_verification_code/{email}"
    const val SHG_FPO_SET_NEW_PASSWORD = "shg_fpo_set_new_password"
    const val SHG_FPO_DASHBOARD = "shg_fpo_dashboard"
    const val SHG_FPO_PROFILE = "shg_fpo_profile"
    const val SHG_FPO_PASSWORD = "shg_fpo_password"

    const val CONSUMER_LOGIN = "consumer_login"
    const val CONSUMER_REGISTER = "consumer_register"
    const val SUBSCRIPTION = "subscription"
    const val CONSUMER_RESET_PASSWORD = "consumer_reset_password"
    const val CONSUMER_VERIFICATION_CODE = "consumer_verification_code/{email}"
    const val CONSUMER_SET_NEW_PASSWORD = "consumer_set_new_password"
    const val CONSUMER_DASHBOARD = "consumer_dashboard"
    const val CONSUMER_PROFILE = "consumer_profile"
    const val CONSUMER_PASSWORD = "consumer_password"
    const val CONSUMER_NOTIFICATIONS = "consumer_notifications"
    const val CONSUMER_USER_PROFILE = "consumer_user_profile"
    const val CONSUMER_EDIT_PROFILE = "consumer_edit_profile"
    const val CONSUMER_MARKETPLACE = "consumer_marketplace"
    const val MY_CART = "my_cart"
    const val MILLET_CATEGORIES = "millet_categories"
    const val PRODUCT_DETAILS = "product_details/{productId}"
    const val TRACEABILITY_JOURNEY = "traceability_journey/{traceabilityId}"
    const val CHECKOUT = "checkout"
    const val PAYMENT = "payment/{orderId}/{amount}"
    const val TRACK_ORDER = "track_order/{orderId}"
    const val MY_ORDERS = "my_orders"

    const val BAJRA_PRODUCT_DETAILS = "bajra_product_details"
    const val BAJRA_CHECKOUT = "bajra_checkout"
    const val BAJRA_TRACEABILITY = "bajra_traceability"
    const val BAJRA_PAYMENT = "bajra_payment"
    const val BAJRA_TRACK_ORDER = "bajra_track_order"

    const val FOXTAIL_PRODUCT_DETAILS = "foxtail_product_details"
    const val FOXTAIL_CHECKOUT = "foxtail_checkout"
    const val FOXTAIL_TRACEABILITY = "foxtail_traceability"
    const val FOXTAIL_PAYMENT = "foxtail_payment"
    const val FOXTAIL_TRACK_ORDER = "foxtail_track_order"

    const val SORGHUM_PRODUCT_DETAILS = "sorghum_product_details"
    const val SORGHUM_CHECKOUT = "sorghum_checkout"
    const val SORGHUM_PAYMENT = "sorghum_payment"
    const val SORGHUM_TRACEABILITY = "sorghum_traceability"
    const val SORGHUM_TRACK_ORDER = "sorghum_track_order"

    const val LITTLE_MILLET_PRODUCT_DETAILS = "little_millet_product_details"
    const val LITTLE_MILLET_CHECKOUT = "little_millet_checkout"
    const val LITTLE_MILLET_PAYMENT = "little_millet_payment"
    const val LITTLE_MILLET_TRACEABILITY = "little_millet_traceability"
    const val LITTLE_MILLET_TRACK_ORDER = "little_millet_track_order"

    const val KODO_MILLET_PRODUCT_DETAILS = "kodo_millet_product_details"
    const val KODO_MILLET_CHECKOUT = "kodo_millet_checkout"
    const val KODO_MILLET_PAYMENT = "kodo_millet_payment"
    const val KODO_MILLET_TRACEABILITY = "kodo_millet_traceability"
    const val KODO_MILLET_TRACK_ORDER = "kodo_millet_track_order"

    const val PROSO_MILLET_PRODUCT_DETAILS = "proso_millet_product_details"
    const val PROSO_MILLET_CHECKOUT = "proso_millet_checkout"
    const val PROSO_MILLET_PAYMENT = "proso_millet_payment"
    const val PROSO_MILLET_TRACEABILITY = "proso_millet_traceability"
    const val PROSO_MILLET_TRACK_ORDER = "proso_millet_track_order"

    const val BARNYARD_MILLET_PRODUCT_DETAILS = "barnyard_millet_product_details"
    const val BARNYARD_MILLET_CHECKOUT = "barnyard_millet_checkout"
    const val BARNYARD_MILLET_PAYMENT = "barnyard_millet_payment"
    const val BARNYARD_MILLET_TRACEABILITY = "barnyard_millet_traceability"
    const val BARNYARD_MILLET_TRACK_ORDER = "barnyard_millet_track_order"

    const val NOTIFICATIONS = "notifications"
    const val USER_PROFILE = "user_profile"
    const val EDIT_PROFILE = "edit_profile"
    const val ADD_MILLET_SUPPLY = "add_millet_supply"
    const val MY_SUPPLY_LIST = "my_supply_list"
    const val ORDERS_RECEIVED = "orders_received"
    const val ORDER_DETAILS = "order_details/{orderId}"
    const val FINGER_MILLET_ORDER_DETAILS = "finger_millet_order_details"
    const val FOXTAIL_MILLET_ORDER_DETAILS = "foxtail_millet_order_details"
    const val PAYMENT_HISTORY = "payment_history"
    const val LOGISTICS_STATUS = "logistics_status/{supplyId}"
    const val MARKET_PRICES = "market_prices"
    const val SALES_SUMMARY = "sales_summary"
    const val SHG_USER_PROFILE = "shg_user_profile"
    const val FARMER_SUPPLIES = "farmer_supplies"
    const val ADD_PRODUCT_LISTING = "add_product_listing?supplyId={supplyId}&milletType={milletType}&quantity={quantity}&qualityGrade={qualityGrade}"
    const val MY_PRODUCTS = "my_products"
    const val LOGISTICS_ASSIGNMENT = "logistics_assignment"
    const val SHG_PAYMENT_HISTORY = "shg_payment_history"
    const val TRACEABILITY_RECORDS = "traceability_records"
    const val SHG_ANALYTICS = "shg_analytics"

    // Generic routes
    const val LOGIN = "login"
    const val RESET_PASSWORD = "reset_password"
    const val VERIFICATION_CODE = "verification_code"
    const val SET_NEW_PASSWORD = "set_new_password"
    const val PASSWORD = "password"
}
